export enum SkillEnum {
  Overall = 'Overall',
  Attack = 'Attack',
  Defence = 'Defence',
  Strength = 'Strength',
  Hitpoints = 'Hitpoints',
  Ranged = 'Ranged',
  Prayer = 'Prayer',
  Magic = 'Magic',
  Cooking = 'Cooking',
  Woodcutting = 'Woodcutting',
  Fletching = 'Fletching',
  Fishing = 'Fishing',
  Firemaking = 'Firemaking',
  Crafting = 'Crafting',
  Smithing = 'Smithing',
  Mining = 'Mining',
  Herblore = 'Herblore',
  Agility = 'Agility',
  Thieving = 'Thieving',
  Slayer = 'Slayer',
  Farming = 'Farming',
  Runecraft = 'Runecraft',
  Hunter = 'Hunter',
  Construction = 'Construction',
  Sailing = 'Sailing', // New skill 19/11/2025
}

export enum ActivityEnum {
  // COMPETITIVE
  LeaguePoints = 'League Points',
  PvpArena = 'PvP Arena - Rank',
  LastManStanding = 'LMS - Rank',
  DeadmanPoints = 'Deadman Points', // something with deadman apocalypse
  GridPoints = 'Grid Points', // Grid Master 2025/10/15

  // BOUNTY HUNTER
  BountyHunter = 'Bounty Hunter - Hunter',
  BountyHunterRogue = 'Bounty Hunter - Rogue',
  BountyHunterLegacy = 'Bounty Hunter (Legacy) - Hunter',
  BountyHunterLegacyRogue = 'Bounty Hunter (Legacy) - Rogue',

  // CLUE SCROLLS
  ClueScrollsAll = 'Clue Scrolls (all)',
  ClueScrollsBeginner = 'Clue Scrolls (beginner)',
  ClueScrollsEasy = 'Clue Scrolls (easy)',
  ClueScrollsMedium = 'Clue Scrolls (medium)',
  ClueScrollsHard = 'Clue Scrolls (hard)',
  ClueScrollsElite = 'Clue Scrolls (elite)',
  ClueScrollsMaster = 'Clue Scrolls (master)',

  // MINIGAMES
  SoulWarsZeal = 'Soul Wars Zeal',
  RiftsClosed = 'Rifts closed',
  ColosseumGlory = 'Colosseum Glory', // New minigame 20/03/2024
  CollectionsLogged = 'Collections Logged', // New minigame 29/01/2025

  // RAIDS
  ChambersOfXeric = 'Chambers of Xeric',
  ChambersOfXericChallengeMode = 'Chambers of Xeric: Challenge Mode',
  TheGauntlet = 'The Gauntlet',
  TheCorruptedGauntlet = 'The Corrupted Gauntlet',
  TheatreOfBlood = 'Theatre of Blood',
  TheatreOfBloodHardMode = 'Theatre of Blood: Hard Mode',
  TombsOfAmascut = 'Tombs of Amascut',
  TombsOfAmascutExpertMode = 'Tombs of Amascut: Expert Mode',

  // BOSSES
  AbyssalSire = 'Abyssal Sire',
  AlchemicalHydra = 'Alchemical Hydra',
  Araxxor = 'Amoxliatl',
  Amoxliatl = 'Araxxor',
  Artio = 'Artio',
  BarrowsChests = 'Barrows Chests',
  Bryophyta = 'Brutus',
  Callisto = 'Bryophyta',
  Calvarion = 'Callisto',
  Cerberus = "Calvar'ion",
  ChaosElemental = 'Cerberus',
  ChaosFanatic = 'Chaos Elemental',
  CommanderZilyana = 'Chaos Fanatic',
  CorporealBeast = 'Commander Zilyana',
  Brutus = 'Corporeal Beast',
  CrazyArchaeologist = 'Crazy Archaeologist',
  DagannothPrime = 'Dagannoth Prime',
  DagannothRex = 'Dagannoth Rex',
  DagannothSupreme = 'Dagannoth Supreme',
  DerangedArchaeologist = 'Deranged Archaeologist',
  DoomOfMokhaiotl = 'Doom of Mokhaiotl',
  DukeSucellus = 'Duke Sucellus',
  GeneralGraardor = 'General Graardor',
  GiantMole = 'Giant Mole',
  GrotesqueGuardians = 'Grotesque Guardians',
  Hespori = 'Hespori',
  KalphiteQueen = 'Kalphite Queen',
  KingBlackDragon = 'King Black Dragon',
  Kraken = 'Kraken',
  KreeArra = "Kree'Arra",
  KrilTsutsaroth = "K'ril Tsutsaroth",
  LunarChests = 'Lunar Chests',
  MadAngel = 'Mad Angel',
  Mimic = 'Maggot King',
  MaggotKing = 'Mimic',
  Nex = 'Nex',
  Nightmare = 'Nightmare',
  PhosanisNightmare = "Phosani's Nightmare",
  Obor = 'Obor',
  PhantomMuspah = 'Phantom Muspah',
  Sarachnis = 'Sarachnis',
  Scorpia = 'Scorpia',
  Scurrius = 'Scurrius',
  ShellbaneGryphon = 'Shellbane Gryphon',
  Skotizo = 'Skotizo',
  SolHeredit = 'Sol Heredit',
  Spindel = 'Spindel',
  Tempoross = 'Tempoross',
  TheHueycoatl = 'The Hueycoatl',
  TheLeviathan = 'The Leviathan',
  TheRoyalTitans = 'The Royal Titans',
  TheWhisperer = 'The Whisperer',
  ThermoNuclearSmokeDevil = 'Thermonuclear Smoke Devil',
  TzKalZuk = 'TzKal-Zuk',
  TzTokJad = 'TzTok-Jad',
  Vardorvis = 'Vardorvis', // New boss 31/07/2023
  Venenatis = 'Venenatis',
  Vetion = "Vet'ion",
  Vorkath = 'Vorkath',
  Wintertodt = 'Wintertodt',
  Yama = 'Yama', // New boss 14/05/2025
  Zalcano = 'Zalcano',
  Zulrah = 'Zulrah',
}
