import { ActivityEnum, SkillEnum } from '../../../models/hiscore.enum';
import { ParseOrder } from '../parse-order';

/** Royal Titans */
export const PO_2025_02_05: ParseOrder = [
  SkillEnum.Overall,
  SkillEnum.Attack,
  SkillEnum.Defence,
  SkillEnum.Strength,
  SkillEnum.Hitpoints,
  SkillEnum.Ranged,
  SkillEnum.Prayer,
  SkillEnum.Magic,
  SkillEnum.Cooking,
  SkillEnum.Woodcutting,
  SkillEnum.Fletching,
  SkillEnum.Fishing,
  SkillEnum.Firemaking,
  SkillEnum.Crafting,
  SkillEnum.Smithing,
  SkillEnum.Mining,
  SkillEnum.Herblore,
  SkillEnum.Agility,
  SkillEnum.Thieving,
  SkillEnum.Slayer,
  SkillEnum.Farming,
  SkillEnum.Runecraft,
  SkillEnum.Hunter,
  SkillEnum.Construction,

  ActivityEnum.LeaguePoints,
  ActivityEnum.DeadmanPoints,

  ActivityEnum.BountyHunter,
  ActivityEnum.BountyHunterRogue,
  ActivityEnum.BountyHunterLegacy,
  ActivityEnum.BountyHunterLegacyRogue,

  ActivityEnum.ClueScrollsAll,
  ActivityEnum.ClueScrollsBeginner,
  ActivityEnum.ClueScrollsEasy,
  ActivityEnum.ClueScrollsMedium,
  ActivityEnum.ClueScrollsHard,
  ActivityEnum.ClueScrollsElite,
  ActivityEnum.ClueScrollsMaster,

  ActivityEnum.LastManStanding,
  ActivityEnum.PvpArena,

  ActivityEnum.SoulWarsZeal,
  ActivityEnum.RiftsClosed,
  ActivityEnum.ColosseumGlory,
  ActivityEnum.CollectionsLogged,

  ActivityEnum.AbyssalSire,
  ActivityEnum.AlchemicalHydra,
  ActivityEnum.Amoxliatl,
  ActivityEnum.Araxxor,
  ActivityEnum.Artio,
  ActivityEnum.BarrowsChests,
  ActivityEnum.Bryophyta,
  ActivityEnum.Callisto,
  ActivityEnum.Calvarion,
  ActivityEnum.Cerberus,

  ActivityEnum.ChambersOfXeric,
  ActivityEnum.ChambersOfXericChallengeMode,

  ActivityEnum.ChaosElemental,
  ActivityEnum.ChaosFanatic,
  ActivityEnum.CommanderZilyana,
  ActivityEnum.CorporealBeast,
  ActivityEnum.CrazyArchaeologist,
  ActivityEnum.DagannothPrime,
  ActivityEnum.DagannothRex,
  ActivityEnum.DagannothSupreme,
  ActivityEnum.DerangedArchaeologist,
  ActivityEnum.DukeSucellus,
  ActivityEnum.GeneralGraardor,
  ActivityEnum.GiantMole,
  ActivityEnum.GrotesqueGuardians,
  ActivityEnum.Hespori,
  ActivityEnum.KalphiteQueen,
  ActivityEnum.KingBlackDragon,
  ActivityEnum.Kraken,
  ActivityEnum.KreeArra,
  ActivityEnum.KrilTsutsaroth,
  ActivityEnum.LunarChests,
  ActivityEnum.Mimic,
  ActivityEnum.Nex,
  ActivityEnum.Nightmare,
  ActivityEnum.PhosanisNightmare,
  ActivityEnum.Obor,
  ActivityEnum.PhantomMuspah,
  ActivityEnum.Sarachnis,
  ActivityEnum.Scorpia,
  ActivityEnum.Scurrius,
  ActivityEnum.Skotizo,
  ActivityEnum.SolHeredit,
  ActivityEnum.Spindel,
  ActivityEnum.Tempoross,

  ActivityEnum.TheGauntlet,
  ActivityEnum.TheCorruptedGauntlet,

  ActivityEnum.TheHueycoatl,
  ActivityEnum.TheLeviathan,
  ActivityEnum.TheRoyalTitans,
  ActivityEnum.TheWhisperer,

  ActivityEnum.TheatreOfBlood,
  ActivityEnum.TheatreOfBloodHardMode,

  ActivityEnum.ThermonuclearSmokeDevil,

  ActivityEnum.TombsOfAmascut,
  ActivityEnum.TombsOfAmascutExpertMode,

  ActivityEnum.TzKalZuk,
  ActivityEnum.TzTokJad,
  ActivityEnum.Vardorvis,
  ActivityEnum.Venenatis,
  ActivityEnum.Vetion,
  ActivityEnum.Vorkath,
  ActivityEnum.Wintertodt,
  ActivityEnum.Zalcano,
  ActivityEnum.Zulrah,
];
