name: CI

on:
  push:
    branches: ['main']
    paths:
      - 'lambda/**'
  pull_request:
    branches: ['main']
    paths:
      - 'lambda/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda_function:
          - osrs-tracker_item-info
          - osrs-tracker_item-search
          - osrs-tracker_player-info
          - osrs-tracker_process-items
          - osrs-tracker_process-players
          - osrs-tracker_queue-items
          - osrs-tracker_queue-players

    steps:
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            lambda_function: 
              - ${{ matrix.lambda_function }}

      - if: steps.changes.outputs.lambda_function == 'true'
        name: Checkout
        uses: actions/checkout@v2

      - if: steps.changes.outputs.lambda_function == 'true'
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - if: steps.changes.outputs.lambda_function == 'true'
        run: npm ci

      - if: steps.changes.outputs.lambda_function == 'true'
        run: npm run prettier:ci
