name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  root:
    name: Global Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Prettier
        run: npm run prettier:ci

  lambda:
    name: Lambda CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lambda_function:
          - osrs-tracker_clean-hiscores
          - osrs-tracker_hiscore-parser-validator
          - osrs-tracker_latest-news
          - osrs-tracker_process-players
          - osrs-tracker_queue-players
          - osrs-tracker_refresh-items

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install
        run: npm ci
        working-directory: lambda/${{ matrix.lambda_function }}

      - name: ESlint
        run: npm run lint
        working-directory: lambda/${{ matrix.lambda_function }}

      - name: Prettier
        run: npm run prettier:ci
        working-directory: lambda/${{ matrix.lambda_function }}

      - name: Build
        run: npm run build
        working-directory: lambda/${{ matrix.lambda_function }}
